import { format } from 'date-fns';
import { useDataStore } from '../store/useDataStore';
import { useTaskStore } from '../store/useTaskStore';
import { projectConfigQueries } from '../db/queries';
import { ProgressBar, SeverityBadge, StatusBadge, MilestoneBadge } from '../components/ui/shared';
import { Copy, Printer } from 'lucide-react';
import { useState } from 'react';

export default function Handover() {
  const { risks, issues, decisions, actions, milestones, stakeholders, resources, notes } = useDataStore();
  const { tasks } = useTaskStore();
  const config = projectConfigQueries.get();
  const [copied, setCopied] = useState(false);

  const today = format(new Date(), 'MMMM d, yyyy');
  const activeTasks = tasks.filter(t => !t.isBacklog);
  const openRisks = risks.filter(r => !['closed', 'accepted'].includes(r.status));
  const openIssues = issues.filter(i => ['open', 'in-progress', 'escalated'].includes(i.status));
  const pendingDecisions = decisions.filter(d => ['proposed', 'under-discussion', 'decision-required'].includes(d.status));
  const openActions = actions.filter(a => ['open', 'in-progress'].includes(a.status));
  const pinnedNotes = notes.filter(n => n.isPinned);
  const completionRate = activeTasks.length > 0 ? Math.round((activeTasks.filter(t => t.status === 'done').length / activeTasks.length) * 100) : 0;

  function generateHandover(): string {
    return `# PROJECT HANDOVER DOCUMENT
# ${(config?.name as string) || 'Project'} — ${today}

---

## 1. PROJECT OVERVIEW
- **Name**: ${(config?.name as string) || 'N/A'}
- **Code**: ${(config?.code as string) || 'N/A'}
- **Status**: ${config?.status || 'N/A'}
- **Phase**: ${config?.currentPhase || 'N/A'}
- **Manager**: ${config?.manager || 'N/A'}
- **Sponsor**: ${config?.sponsor || 'N/A'}
- **Target Delivery**: ${config?.targetDate || 'N/A'}
- **Overall Progress**: ${completionRate}%

**Description**: ${config?.description || 'N/A'}

**Business Context**: ${config?.businessContext || 'N/A'}

---

## 2. CURRENT STATUS
- Tasks Total: ${activeTasks.length} (${activeTasks.filter(t => t.status === 'done').length} done, ${activeTasks.filter(t => t.status === 'in-progress').length} in progress)
- Open Issues: ${openIssues.length}
- Open Risks: ${openRisks.length}
- Pending Decisions: ${pendingDecisions.length}
- Open Actions: ${openActions.length}

---

## 3. MILESTONES
${milestones.map(m => `- **${m.name}** — Target: ${m.targetDate || 'N/A'} — Progress: ${m.progress}% — Status: ${m.status}`).join('\n') || '(none)'}

---

## 4. ACTIVE RISKS
${openRisks.map(r => `- [${r.severity.toUpperCase()}] **${r.title}**\n  Owner: ${r.owner || 'N/A'}\n  Mitigation: ${r.mitigationStrategy || 'N/A'}`).join('\n') || '(none)'}

---

## 5. OPEN ISSUES & BLOCKERS
${openIssues.map(i => `- [${i.severity.toUpperCase()}] **${i.title}**\n  Impact: ${i.impact || 'N/A'}\n  Actions: ${i.resolutionActions || 'N/A'}`).join('\n') || '(none)'}

---

## 6. PENDING DECISIONS
${pendingDecisions.map(d => `- **${d.title}** [${d.status}]\n  Owner: ${d.owner || 'N/A'}\n  Deadline: ${d.deadline || 'N/A'}\n  Context: ${d.context?.slice(0, 120) || 'N/A'}`).join('\n') || '(none)'}

---

## 7. KEY STAKEHOLDERS
${stakeholders.map(s => `- **${s.name}** — ${s.role} (${s.organization || 'N/A'}) — ${s.email || 'N/A'}`).join('\n') || '(none)'}

---

## 8. TEAM & RESOURCES
${resources.map(r => `- **${r.name}** — ${r.role} (${r.organization || 'N/A'}) — ${r.allocationPercent}% — ${r.email || 'N/A'}`).join('\n') || '(none)'}

---

## 9. OPEN ACTIONS
${openActions.map(a => `- **${a.action}** — Owner: ${a.owner || 'N/A'} — Due: ${a.dueDate || 'N/A'} — ${a.status}`).join('\n') || '(none)'}

---

## 10. KEY NOTES & REFERENCES
${pinnedNotes.map(n => `### ${n.title}\n${n.content}`).join('\n\n') || '(no pinned notes)'}

---
*Generated by Project Tracking Tool · ${today}*
`;
  }

  function copy() {
    navigator.clipboard.writeText(generateHandover());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div>
      <div className="flex items-center gap-3 mb-6">
        <div><h1 className="page-title">Handover View</h1><p className="page-subtitle">Project state snapshot for handover or replacement briefing · {today}</p></div>
        <div className="ml-auto flex items-center gap-2">
          <button className="btn btn-secondary" onClick={() => window.print()} title="Print or save document as PDF"><Printer size={14} /> Print / Save as PDF</button>
          <button className="btn btn-primary" onClick={copy}><Copy size={14} /> {copied ? '✓ Copied!' : 'Copy Handover Doc'}</button>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}>
        {/* Project identity */}
        <div className="card">
          <div className="card-header"><span className="section-title">Project Identity</span></div>
          <div style={{ padding: '12px 24px', display: 'flex', flexDirection: 'column', gap: 8 }}>
            {[
              { label: 'Project', value: config?.name },
              { label: 'Code', value: config?.code },
              { label: 'Status', value: config?.status },
              { label: 'Phase', value: config?.currentPhase },
              { label: 'Manager', value: config?.manager },
              { label: 'Sponsor', value: config?.sponsor },
              { label: 'Target Date', value: config?.targetDate },
            ].map(({ label, value }) => (
              <div key={label} className="flex gap-2">
                <span style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-muted)', minWidth: 80 }}>{label}:</span>
                <span style={{ fontSize: 12, color: 'var(--text-primary)' }}>{value || '—'}</span>
              </div>
            ))}
            <div style={{ marginTop: 8 }}>
              <div style={{ fontSize: 11, marginBottom: 4, color: 'var(--text-muted)', fontWeight: 700 }}>Progress: {completionRate}%</div>
              <ProgressBar value={completionRate} />
            </div>
          </div>
        </div>

        {/* Status summary */}
        <div className="card">
          <div className="card-header"><span className="section-title">Status Summary</span></div>
          <div style={{ padding: '12px 24px', display: 'flex', flexDirection: 'column', gap: 10 }}>
            {[
              { label: 'Tasks Done', value: `${activeTasks.filter(t => t.status === 'done').length} / ${activeTasks.length}`, color: 'var(--success)' },
              { label: 'In Progress', value: activeTasks.filter(t => t.status === 'in-progress').length, color: 'var(--accent)' },
              { label: 'Blocked', value: activeTasks.filter(t => t.status === 'blocked').length, color: 'var(--danger)' },
              { label: 'Open Issues', value: openIssues.length, color: openIssues.length > 0 ? 'var(--warning)' : 'var(--success)' },
              { label: 'Open Risks', value: openRisks.length, color: openRisks.length > 2 ? 'var(--warning)' : 'var(--text-muted)' },
              { label: 'Pending Decisions', value: pendingDecisions.length, color: pendingDecisions.length > 0 ? 'var(--warning)' : 'var(--success)' },
              { label: 'Open Actions', value: openActions.length, color: 'var(--text-muted)' },
            ].map(({ label, value, color }) => (
              <div key={label} className="flex items-center justify-between">
                <span style={{ fontSize: 12, color: 'var(--text-secondary)' }}>{label}</span>
                <span style={{ fontSize: 14, fontWeight: 700, color }}>{value}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Milestones */}
        <div className="card">
          <div className="card-header"><span className="section-title">Milestones</span></div>
          {milestones.map(m => (
            <div key={m.id} style={{ padding: '8px 24px', borderBottom: '1px solid var(--border-subtle)' }}>
              <div className="flex items-center gap-2">
                <span style={{ fontWeight: 600, fontSize: 12, flex: 1 }}>{m.name}</span>
                <MilestoneBadge status={m.status} />
              </div>
              <div style={{ marginTop: 4 }}><ProgressBar value={m.progress} /></div>
            </div>
          ))}
          {milestones.length === 0 && <div style={{ padding: '16px 24px', color: 'var(--text-muted)', fontSize: 12 }}>No milestones.</div>}
        </div>

        {/* Key Stakeholders */}
        <div className="card">
          <div className="card-header"><span className="section-title">Key Stakeholders</span></div>
          {stakeholders.slice(0, 6).map(s => (
            <div key={s.id} style={{ padding: '8px 24px', borderBottom: '1px solid var(--border-subtle)' }}>
              <div style={{ fontWeight: 600, fontSize: 12 }}>{s.name} — {s.role}</div>
              <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{s.organization} · {s.email}</div>
            </div>
          ))}
        </div>

        {/* Open Risks */}
        <div className="card">
          <div className="card-header"><span className="section-title">Open Risks</span></div>
          {openRisks.slice(0, 6).map(r => (
            <div key={r.id} className="attention-item">
              <SeverityBadge severity={r.severity} />
              <div className="attention-content">
                <div className="attention-title">{r.title}</div>
                <div className="attention-meta">{r.owner || 'Unassigned'}</div>
              </div>
            </div>
          ))}
          {openRisks.length === 0 && <div style={{ padding: '16px 24px', color: 'var(--text-muted)', fontSize: 12 }}>✓ No open risks</div>}
        </div>

        {/* Pinned Notes */}
        {pinnedNotes.length > 0 && (
          <div className="card">
            <div className="card-header"><span className="section-title">Pinned Notes</span></div>
            {pinnedNotes.map(n => (
              <div key={n.id} style={{ padding: '8px 24px', borderBottom: '1px solid var(--border-subtle)' }}>
                <div style={{ fontWeight: 600, fontSize: 12 }}>{n.title}</div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>{n.content.slice(0, 100)}</div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
