import { useState } from 'react';
import { format } from 'date-fns';
import { useTaskStore } from '../store/useTaskStore';
import { useDataStore } from '../store/useDataStore';
import { StatusBadge, SeverityBadge, ActionBadge, DateDisplay } from '../components/ui/shared';
import { ClipboardCheck, Copy } from 'lucide-react';

export default function WeeklyReview() {
  const { tasks } = useTaskStore();
  const { risks, issues, decisions, actions, milestones, communications } = useDataStore();
  const [weekNotes, setWeekNotes] = useState('');
  const [copied, setCopied] = useState(false);

  const today = new Date();
  const todayStr = today.toISOString().split('T')[0];
  const weekAgo = new Date(today); weekAgo.setDate(today.getDate() - 7);
  const weekAgoStr = weekAgo.toISOString().split('T')[0];
  const nextWeek = new Date(today); nextWeek.setDate(today.getDate() + 7);
  const nextWeekStr = nextWeek.toISOString().split('T')[0];

  const activeTasks = tasks.filter(t => !t.isBacklog);
  const doneThisWeek = activeTasks.filter(t => t.status === 'done');
  const inProgress = activeTasks.filter(t => t.status === 'in-progress');
  const overdue = activeTasks.filter(t => t.dueDate && t.dueDate < todayStr && !['done', 'cancelled'].includes(t.status));
  const blocked = activeTasks.filter(t => t.status === 'blocked' || t.status === 'waiting');
  const dueNextWeek = activeTasks.filter(t => t.dueDate && t.dueDate >= todayStr && t.dueDate <= nextWeekStr && !['done', 'cancelled'].includes(t.status));

  const openIssues = issues.filter(i => ['open', 'in-progress', 'escalated'].includes(i.status));
  const criticalRisks = risks.filter(r => r.severity === 'critical' && r.status !== 'closed');
  const pendingDecisions = decisions.filter(d => ['proposed', 'under-discussion', 'decision-required'].includes(d.status));
  const overdueActions = actions.filter(a => a.dueDate && a.dueDate < todayStr && a.status !== 'done');
  const awaitingComms = communications.filter(c => c.status === 'awaiting-response');

  const upcomingMilestones = milestones.filter(m => m.targetDate && m.targetDate >= todayStr && m.targetDate <= nextWeekStr);

  const completion = activeTasks.length > 0 ? Math.round((activeTasks.filter(t => t.status === 'done').length / activeTasks.length) * 100) : 0;

  function generateReport(): string {
    return `# Weekly Status Report — ${format(today, 'MMMM d, yyyy')}

## 📊 Project Health
- **Overall Progress**: ${completion}%
- **Tasks In Progress**: ${inProgress.length}
- **Overdue Tasks**: ${overdue.length}
- **Blocked Tasks**: ${blocked.length}
- **Open Issues**: ${openIssues.length}
- **Critical Risks**: ${criticalRisks.length}
- **Awaiting Response (Comms)**: ${awaitingComms.length}

## ✅ Completed This Period
${doneThisWeek.map(t => `- [DONE] ${t.title} (Owner: ${t.owner || 'N/A'})`).join('\n') || '- (none recorded)'}

## 🔄 In Progress
${inProgress.map(t => `- ${t.title} — Owner: ${t.owner || 'N/A'}${t.dueDate ? ` — Due: ${t.dueDate}` : ''}`).join('\n') || '- (none)'}

## 🔴 Blocked / Waiting
${blocked.map(t => `- [${t.status.toUpperCase()}] ${t.title}: ${t.blockingReason || 'No reason'}`).join('\n') || '- (none)'}

## ⚠️ Issues & Risks
${openIssues.map(i => `- 🚫 [Issue/${i.severity}] ${i.title}`).join('\n')}
${criticalRisks.map(r => `- ⚠️ [Risk/Critical] ${r.title}`).join('\n') || '(no critical risks)'}

## 📅 Due Next 7 Days
${dueNextWeek.map(t => `- ${t.title} — Due: ${t.dueDate} — Owner: ${t.owner || 'N/A'}`).join('\n') || '- (none)'}

## 🚀 Upcoming Milestones
${upcomingMilestones.map(m => `- ${m.name} — Due: ${m.targetDate} (${m.progress}% complete)`).join('\n') || '- (none this week)'}

## ⏳ Pending Decisions
${pendingDecisions.map(d => `- [${d.status.toUpperCase()}] ${d.title} — Owner: ${d.owner || 'N/A'}${d.deadline ? ` — Deadline: ${d.deadline}` : ''}`).join('\n') || '- (none)'}

## 📬 Awaiting Response
${awaitingComms.map(c => `- ${c.subject} → ${c.recipients}${c.expectedResponseDate ? ` (expected ${c.expectedResponseDate})` : ''}`).join('\n') || '- (none)'}

## 📝 Additional Notes
${weekNotes || '(none)'}

---
*Generated by Project Tracking Tool · ${format(today, 'MMMM d, yyyy HH:mm')}*
`;
  }

  function copyReport() {
    navigator.clipboard.writeText(generateReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div>
      <div className="flex items-center gap-3 mb-6">
        <div><h1 className="page-title">Weekly Review</h1><p className="page-subtitle">Status snapshot · {format(today, 'MMMM d, yyyy')}</p></div>
        <button className="btn btn-primary ml-auto" onClick={copyReport}>
          <Copy size={14} /> {copied ? '✓ Copied!' : 'Copy Status Report'}
        </button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, marginBottom: 20 }}>
        {/* Completed */}
        <div className="card">
          <div className="card-header"><ClipboardCheck size={16} color="var(--success)" /><span className="section-title">Completed</span><span className="badge status-done" style={{ marginLeft: 'auto' }}>{doneThisWeek.length}</span></div>
          {doneThisWeek.slice(0, 8).map(t => <div key={t.id} className="attention-item"><StatusBadge status="done" /><div className="attention-content"><div className="attention-title">{t.title}</div><div className="attention-meta">{t.owner || 'Unassigned'}</div></div></div>)}
          {doneThisWeek.length === 0 && <div style={{ padding: '16px 24px', color: 'var(--text-muted)', fontSize: 'var(--text-sm)' }}>No tasks marked done yet.</div>}
        </div>

        {/* In Progress */}
        <div className="card">
          <div className="card-header"><span className="section-title">In Progress</span><span className="badge status-in-progress" style={{ marginLeft: 'auto' }}>{inProgress.length}</span></div>
          {inProgress.slice(0, 8).map(t => <div key={t.id} className="attention-item"><StatusBadge status="in-progress" /><div className="attention-content"><div className="attention-title">{t.title}</div><div className="attention-meta">{t.owner || 'Unassigned'}{t.dueDate && <> · <DateDisplay date={t.dueDate} /></>}</div></div></div>)}
          {inProgress.length === 0 && <div style={{ padding: '16px 24px', color: 'var(--text-muted)', fontSize: 'var(--text-sm)' }}>Nothing in progress.</div>}
        </div>

        {/* Blocked & Overdue */}
        <div className="card">
          <div className="card-header"><span className="section-title" style={{ color: 'var(--danger)' }}>⚠ Blocked & Overdue</span></div>
          {blocked.map(t => <div key={t.id} className="attention-item" style={{ background: 'var(--danger-bg)' }}><StatusBadge status={t.status} /><div className="attention-content"><div className="attention-title">{t.title}</div><div className="attention-meta" style={{ color: 'var(--danger)' }}>{t.blockingReason?.slice(0, 60) || 'Waiting'}</div></div></div>)}
          {overdue.filter(t => t.status !== 'blocked' && t.status !== 'waiting').map(t => <div key={t.id} className="attention-item"><StatusBadge status={t.status} /><div className="attention-content"><div className="attention-title">{t.title}</div><div className="attention-meta" style={{ color: 'var(--danger)' }}>Due: {t.dueDate}</div></div></div>)}
          {blocked.length === 0 && overdue.length === 0 && <div style={{ padding: '16px 24px', color: 'var(--text-muted)', fontSize: 'var(--text-sm)' }}>✓ Nothing blocked or overdue.</div>}
        </div>

        {/* Due Next Week */}
        <div className="card">
          <div className="card-header"><span className="section-title">Due Next 7 Days</span><span className="badge status-waiting" style={{ marginLeft: 'auto' }}>{dueNextWeek.length}</span></div>
          {dueNextWeek.slice(0, 8).map(t => <div key={t.id} className="attention-item"><div className="attention-content"><div className="attention-title">{t.title}</div><div className="attention-meta">{t.owner || 'Unassigned'} · <DateDisplay date={t.dueDate} /></div></div></div>)}
          {dueNextWeek.length === 0 && <div style={{ padding: '16px 24px', color: 'var(--text-muted)', fontSize: 'var(--text-sm)' }}>Nothing due next week.</div>}
        </div>
      </div>

      {/* Open risks & issues summary */}
      <div className="card" style={{ marginBottom: 20 }}>
        <div className="card-header"><span className="section-title">Open Risks & Issues</span></div>
        <div style={{ padding: '8px 24px', display: 'flex', flexDirection: 'column', gap: 6 }}>
          {criticalRisks.map(r => <div key={r.id} className="flex items-center gap-2" style={{ fontSize: 13 }}><SeverityBadge severity="critical" /><span>{r.title}</span></div>)}
          {openIssues.map(i => <div key={i.id} className="flex items-center gap-2" style={{ fontSize: 13 }}><SeverityBadge severity={i.severity} /><span>{i.title}</span></div>)}
          {criticalRisks.length === 0 && openIssues.length === 0 && <div style={{ color: 'var(--text-muted)', fontSize: 'var(--text-sm)' }}>✓ No critical risks or open issues.</div>}
        </div>
      </div>

      {/* Notes */}
      <div className="card">
        <div className="card-header"><span className="section-title">Additional Notes for Report</span></div>
        <div style={{ padding: '12px 24px' }}>
          <textarea className="textarea" rows={6} value={weekNotes} onChange={e => setWeekNotes(e.target.value)} placeholder="Add context, achievements, blockers, next week focus area..." />
        </div>
      </div>
    </div>
  );
}
